### ISSUE TITLE
fake?

### ISSUE THREAD

**Issue by kali-unknown** [leakwallet/hunter-demo#1]
winbal = random_winner_balance()
random winner balance? that probably means its fake

**Comment by leakwallet** [comment]
Hi Kali-unknown,

Thank you for your feedback!

I want to clarify that it's not fake. The version we uploaded on GitHub is just a demo of the original software. We designed this demo to show how the actual software functions, but it's not meant for making any money. You can find all the details about this demo software in the readme.md file.

If you're interested in the full version with all its features, please visit our website at leakwallet.com.
